# Generated by Django 2.1.5 on 2019-05-07 08:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_stripepaymentshistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StripePaymentsHistory',
            new_name='StripePaymentHistory',
        ),
    ]
