# Generated by Django 2.1.5 on 2019-05-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20190507_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomerid',
            name='card',
            field=models.CharField(default='21345546443544', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripecustomerid',
            name='source_token',
            field=models.CharField(default='321423423423', max_length=300),
            preserve_default=False,
        ),
    ]
