# Generated by Django 2.1.5 on 2019-05-07 13:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0006_auto_20190507_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StripeCustomerId',
            new_name='StripeCustomer',
        ),
    ]
