# Generated by Django 2.1.5 on 2019-05-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20190507_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='card',
            field=models.CharField(max_length=16),
        ),
    ]
