# Generated by Django 2.1.5 on 2019-05-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20190507_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='status_code',
            new_name='status_message',
        ),
    ]
