# Generated by Django 2.1.5 on 2019-05-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20190508_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='status_message',
            field=models.CharField(max_length=100),
        ),
    ]
