# Generated by Django 2.1.5 on 2019-05-08 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_paymenthistory_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.StripeCustomer'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.CustomerOrders'),
        ),
    ]
