# Generated by Django 2.1.5 on 2019-05-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_auto_20190508_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='name',
            field=models.CharField(default='deepak', max_length=40),
            preserve_default=False,
        ),
    ]
