# Generated by Django 2.1.5 on 2019-05-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_stripecustomer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
