# Generated by Django 2.1.5 on 2019-05-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_auto_20190517_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='card',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='source_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='stripe_cus_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
