# Generated by Django 2.1.5 on 2019-06-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_auto_20190517_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(choices=[('1', 'Card'), ('3', 'Net banking'), ('2', 'Cash on delivery')], max_length=30),
        ),
    ]
