# Generated by Django 2.1.5 on 2019-07-31 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_auto_20190731_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
