# Generated by Django 2.1.5 on 2019-10-16 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBodyMeasurementData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('1', 'male'), ('2', 'female'), ('3', 'kids')], max_length=20)),
                ('height', models.CharField(default=0, max_length=20)),
                ('chest', models.CharField(default=0, max_length=20)),
                ('butts', models.CharField(default=0, max_length=20)),
                ('waist', models.CharField(default=0, max_length=20)),
                ('thigh', models.CharField(default=0, max_length=20)),
                ('arm', models.CharField(default=0, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
