# Generated by Django 2.1.5 on 2019-03-06 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer_stylist', '0006_stylistdesignercategory'),
        ('product', '0002_auto_20190223_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usercategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='designer_stylist.StylistDesignerCategory'),
        ),
    ]
