# Generated by Django 2.1.5 on 2019-03-06 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer_stylist', '0007_stylistdesignersection'),
        ('product', '0003_product_usercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usersection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='designer_stylist.StylistDesignerSection'),
        ),
    ]
