# Generated by Django 2.1.5 on 2019-03-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190307_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAvailableColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='productcolourswithquantity',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='productcolourswithquantity',
            name='product_available_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AlterField(
            model_name='productavailablesize',
            name='size',
            field=models.CharField(max_length=60),
        ),
        migrations.DeleteModel(
            name='ProductColoursWithQuantity',
        ),
        migrations.AddField(
            model_name='productavailablecolour',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
