# Generated by Django 2.1.5 on 2019-03-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190308_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty_sold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
