# Generated by Django 2.1.5 on 2019-03-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.ManyToManyField(blank=True, to='product.Colour'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='product.Size'),
        ),
    ]
