# Generated by Django 2.1.5 on 2019-03-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20190312_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.SubCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subsubcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.SubSubCategory'),
        ),
    ]
