# Generated by Django 2.1.5 on 2019-03-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20190312_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='size',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
