# Generated by Django 2.1.5 on 2019-03-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20190312_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
