# Generated by Django 2.1.5 on 2019-03-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_colour_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colour',
            name='code',
        ),
        migrations.AddField(
            model_name='colour',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
