# Generated by Django 2.1.5 on 2019-03-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20190327_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colour',
            old_name='name',
            new_name='code',
        ),
    ]
