# Generated by Django 2.1.5 on 2019-03-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20190327_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerproductcart',
            old_name='selected_color',
            new_name='selected_colour',
        ),
        migrations.AddField(
            model_name='customerproductwishlist',
            name='selected_colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Size'),
        ),
        migrations.AddField(
            model_name='customerproductwishlist',
            name='selected_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Colour'),
        ),
    ]
