# Generated by Django 2.1.5 on 2019-03-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20190327_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponcode',
            old_name='is_for_all',
            new_name='is_for_all_user',
        ),
        migrations.RemoveField(
            model_name='couponcode',
            name='is_for_selected_users',
        ),
        migrations.AddField(
            model_name='couponcode',
            name='coupon_type',
            field=models.CharField(choices=[(1, 'percent'), (2, 'amount')], default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponcode',
            name='max_amount',
            field=models.CharField(default='1000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponcode',
            name='value',
            field=models.CharField(default='100', max_length=10),
            preserve_default=False,
        ),
    ]
