# Generated by Django 2.1.5 on 2019-03-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20190328_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='usage_limit',
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='coupon_type',
            field=models.CharField(choices=[('1', 'percent'), ('2', 'amount')], max_length=10),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='max_amount',
            field=models.CharField(max_length=10),
        ),
    ]
