# Generated by Django 2.1.5 on 2019-03-28 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20190328_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='selected_product',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='selected_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
