# Generated by Django 2.1.5 on 2019-03-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20190328_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='max_amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='usage_limit',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
