# Generated by Django 2.1.5 on 2019-04-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20190328_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_from', models.CharField(max_length=10)),
                ('dist_to', models.CharField(max_length=10)),
                ('charges', models.CharField(max_length=10)),
            ],
        ),
    ]
