# Generated by Django 2.1.5 on 2019-04-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_deliverymanagement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryManagement',
            new_name='DeliveryDistanceManagement',
        ),
    ]
