# Generated by Django 2.1.5 on 2019-04-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20190401_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
