# Generated by Django 2.1.5 on 2019-04-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_product_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydistancemanagement',
            name='charges',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliverydistancemanagement',
            name='dist_from',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deliverydistancemanagement',
            name='dist_to',
            field=models.IntegerField(),
        ),
    ]
