# Generated by Django 2.1.5 on 2019-04-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20190404_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='CatBannerImg'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='SubCatBannerImg'),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='SubSubCatBannerImg'),
        ),
    ]
