# Generated by Django 2.1.5 on 2019-04-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20190409_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='CatBannerImg'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='SubCatBannerImg'),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='SubSubCatBannerImg'),
        ),
    ]
