# Generated by Django 2.1.5 on 2019-04-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20190409_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproductcart',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
