# Generated by Django 2.1.5 on 2019-04-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_product_available_colours'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='product.ProductAvailableSizeWithQty'),
        ),
    ]
