# Generated by Django 2.1.5 on 2019-04-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_colours',
        ),
    ]
