# Generated by Django 2.1.5 on 2019-04-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_remove_product_available_colours'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_colours',
            field=models.ManyToManyField(blank=True, related_name='_product_available_colours_+', to='product.Product'),
        ),
    ]
