# Generated by Django 2.1.5 on 2019-04-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_product_available_colours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_colours',
        ),
        migrations.AddField(
            model_name='product',
            name='available_subproducts',
            field=models.ManyToManyField(blank=True, related_name='_product_available_subproducts_+', to='product.Product'),
        ),
    ]
