# Generated by Django 2.1.5 on 2019-04-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_auto_20190429_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actual_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
