# Generated by Django 2.1.5 on 2019-04-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_auto_20190429_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pattern',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
