# Generated by Django 2.1.5 on 2019-04-30 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_auto_20190430_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productavailablesizewithqty',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Size'),
        ),
    ]
