# Generated by Django 2.1.5 on 2019-04-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20190430_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproductcart',
            name='selected_colour',
        ),
    ]
