# Generated by Django 2.1.5 on 2019-04-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_remove_customerproductcart_selected_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_img',
            field=models.ImageField(blank=True, default='Product/default', upload_to='Product/MainImg'),
        ),
    ]
