# Generated by Django 2.1.5 on 2019-05-01 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_auto_20190430_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAvailableColourWithSizeQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_price', models.PositiveIntegerField(blank=True, null=True)),
                ('special_price', models.PositiveIntegerField(blank=True, null=True)),
                ('offer', models.CharField(blank=True, max_length=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('colour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Colour')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImageByColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Product/OtherImg')),
                ('product_colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductAvailableColourWithSizeQty')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSizeWithQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('initial_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('available_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='productavailablesizewithqty',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_subproducts',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='isfree_delivery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_date_from',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_date_to',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_status',
        ),
        migrations.DeleteModel(
            name='ProductAvailableSizeWithQty',
        ),
        migrations.AddField(
            model_name='productavailablecolourwithsizeqty',
            name='size_and_qty',
            field=models.ManyToManyField(blank=True, to='product.ProductSizeWithQty'),
        ),
    ]
