# Generated by Django 2.1.5 on 2019-05-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_auto_20190501_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_colours',
            field=models.ManyToManyField(blank=True, to='product.ProductAvailableColourWithSizeQty'),
        ),
    ]
