# Generated by Django 2.1.5 on 2019-05-01 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_auto_20190501_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproductwishlist',
            name='selected_colour',
            field=models.ForeignKey(null=True,blank=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductAvailableColourWithSizeQty'),
        ),
    ]
