# Generated by Django 2.1.5 on 2019-05-01 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_auto_20190501_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproductcart',
            name='selected_colour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductAvailableColourWithSizeQty'),
        ),
        migrations.AlterField(
            model_name='customerproductwishlist',
            name='selected_size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
