# Generated by Django 2.1.5 on 2019-05-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_auto_20190501_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
