# Generated by Django 2.1.5 on 2019-05-01 13:47

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_product_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_of_min',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
