# Generated by Django 2.1.5 on 2019-05-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0058_auto_20190502_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_row',
            field=models.BooleanField(default=True),
        ),
    ]
