# Generated by Django 2.1.5 on 2019-05-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_product_is_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
