# Generated by Django 2.1.5 on 2019-05-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_couponcode_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='new_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
