# Generated by Django 2.1.5 on 2019-05-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_auto_20190523_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsizewithqty',
            name='sort_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
