# Generated by Django 2.1.5 on 2019-05-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_productsizewithqty_sort_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
