# Generated by Django 2.1.5 on 2019-05-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0063_auto_20190528_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_role',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
