# Generated by Django 2.1.5 on 2019-05-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_product_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_role',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
