# Generated by Django 2.1.5 on 2019-06-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0067_product_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproductcart',
            name='is_product_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
