# Generated by Django 2.1.5 on 2019-06-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0068_customerproductcart_is_product_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproductcart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
    ]
