# Generated by Django 2.1.5 on 2019-06-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_auto_20190607_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproductcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
