# Generated by Django 2.1.5 on 2019-06-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0070_auto_20190607_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qty_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
