# Generated by Django 2.1.5 on 2019-10-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0074_productimagefor3dview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimagefor3dview',
            old_name='image1',
            new_name='back',
        ),
        migrations.RenameField(
            model_name='productimagefor3dview',
            old_name='image2',
            new_name='front',
        ),
    ]
