# Generated by Django 2.1.5 on 2019-10-17 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0075_auto_20191017_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimagefor3dview',
            name='colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductAvailableColourWithSizeQty'),
        ),
    ]
