# Generated by Django 2.1.5 on 2019-10-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0076_productimagefor3dview_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimagefor3dview',
            name='wearable_type',
            field=models.CharField(choices=[('1', 'Topwear'), ('2', 'Bottomwear'), ('3', 'Fullwear')], default='1', max_length=20),
        ),
    ]
