# Generated by Django 2.1.5 on 2019-10-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_productimagefor3dview_wearable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_3d_view_available',
            field=models.BooleanField(default=False),
        ),
    ]
