# Generated by Django 2.1.5 on 2019-10-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0078_product_is_3d_view_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_3d_view_available',
        ),
    ]
