# Generated by Django 2.1.5 on 2019-07-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_audiovideocharges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiovideocharges',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserOtherInfo'),
        ),
    ]
