# Generated by Django 2.1.5 on 2019-07-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20190725_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiovideocharges',
            name='currency',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
