# Generated by Django 2.1.5 on 2019-02-20 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user/achievement_img')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('3', 'designer'), ('4', 'stylist')], max_length=2)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('profileimg', models.ImageField(blank=True, null=True, upload_to='user/profile_img')),
                ('coverimg', models.ImageField(blank=True, null=True, upload_to='user/cover_img')),
                ('des', models.TextField()),
                ('product_sold', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_views', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='designerprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer_stylist.Profile'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='designerprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer_stylist.Profile'),
        ),
    ]
