# Generated by Django 2.1.5 on 2019-02-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_stylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
