# Generated by Django 2.1.5 on 2019-02-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer_stylist', '0002_achievement_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='designerprofile',
        ),
        migrations.AddField(
            model_name='image',
            name='achievement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='designer_stylist.Achievement'),
            preserve_default=False,
        ),
    ]
