# Generated by Django 2.1.5 on 2019-03-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_stylist', '0003_auto_20190222_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('3', 'designer'), ('4', 'stylist'), ('5', 'manufacturer')], max_length=2),
        ),
    ]
