# Generated by Django 2.1.5 on 2019-03-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer_stylist', '0004_auto_20190304_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('3', 'designer'), ('4', 'stylist'), ('5', 'manufacturer')], max_length=13),
        ),
    ]
