# Generated by Django 2.1.5 on 2019-02-20 10:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phonenum', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=30)),
                ('area_street', models.CharField(blank=True, max_length=30, null=True)),
                ('flat_buld', models.CharField(blank=True, max_length=30, null=True)),
                ('landmark', models.CharField(blank=True, max_length=30, null=True)),
                ('addr_type', models.CharField(choices=[('work', 'Work'), ('home', 'Home'), ('other', 'Other')], max_length=10)),
                ('lat', models.CharField(max_length=20)),
                ('lag', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('des', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserOtherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isprofile_created', models.BooleanField(default=False)),
                ('profileimg', models.ImageField(blank=True, null=True, upload_to='user/profileimg')),
                ('coverimg', models.ImageField(blank=True, null=True, upload_to='user/coverimg')),
                ('phonenum', models.CharField(max_length=10, unique=True)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('isnumverify', models.BooleanField(default=False)),
                ('ismailverify', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('addr_one', models.CharField(blank=True, max_length=50, null=True)),
                ('addr_two', models.CharField(blank=True, max_length=50, null=True)),
                ('addr_three', models.CharField(blank=True, max_length=50, null=True)),
                ('device_token', models.CharField(blank=True, max_length=500, null=True)),
                ('device_type', models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'IOS'), ('web', 'Web')], max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ManyToManyField(to='accounts.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
