# Generated by Django 2.1.5 on 2019-02-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotherinfo',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
