# Generated by Django 2.1.5 on 2019-02-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190225_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotherinfo',
            name='addr_one',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
