# Generated by Django 2.1.5 on 2019-02-26 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190226_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotherinfo',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
