# Generated by Django 2.1.5 on 2019-02-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userotherinfo_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotherinfo',
            name='phonenum',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
