# Generated by Django 2.1.5 on 2019-03-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190228_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='id',
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
