# Generated by Django 2.1.5 on 2019-03-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190302_1401'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userotherinfo',
            unique_together={('phonenum', 'country_code')},
        ),
    ]
