# Generated by Django 2.1.5 on 2019-03-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190305_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotherinfo',
            name='phonenum',
            field=models.CharField(max_length=14),
        ),
    ]
