# Generated by Django 2.1.5 on 2019-04-10 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phonenum', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=40)),
                ('pincode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=30)),
                ('area_street', models.CharField(blank=True, max_length=60, null=True)),
                ('flat_building', models.CharField(blank=True, max_length=60, null=True)),
                ('addr_type', models.CharField(choices=[('1', 'Work'), ('2', 'Home'), ('3', 'Other')], max_length=10)),
                ('landmark', models.CharField(blank=True, max_length=40, null=True)),
                ('lat', models.CharField(max_length=30)),
                ('lag', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
