# Generated by Django 2.1.5 on 2019-04-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190411_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='area_street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='flat_building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
