# Generated by Django 2.1.5 on 2019-04-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_customerorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
