# Generated by Django 2.1.5 on 2019-04-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_customerproductcart_is_ordered'),
        ('orders', '0006_customeraddress_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='coupon_applied',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.CouponCode'),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='coupon_off',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='grand_total',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='is_coupon_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='item',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='order_status',
            field=models.CharField(blank=True, choices=[('1', 'Ordered'), ('2', 'Net banking'), ('3', 'Cash on delivery')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='saved_amount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='shipping_charges',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
