# Generated by Django 2.1.5 on 2019-04-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190412_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerorders',
            old_name='coupon_applied',
            new_name='coupon_id',
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='order_status',
            field=models.CharField(blank=True, choices=[('1', 'Ordered'), ('2', 'Packed'), ('3', 'Shipped'), ('4', 'Delivered')], max_length=2, null=True),
        ),
    ]
