# Generated by Django 2.1.5 on 2019-04-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190412_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='order_status',
            field=models.CharField(choices=[('1', 'Ordered'), ('2', 'Packed'), ('3', 'Shipped'), ('4', 'Delivered')], default=1, max_length=2),
        ),
    ]
