# Generated by Django 2.1.5 on 2019-04-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190415_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='order_status',
            field=models.CharField(choices=[('1', 'Ordered'), ('2', 'Packed'), ('3', 'Shipped'), ('4', 'Delivered'), ('5', 'Canceled')], default=1, max_length=2),
        ),
    ]
