# Generated by Django 2.1.5 on 2019-04-18 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20190412_1521'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_auto_20190418_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('1', 'Ordered'), ('2', 'Packed'), ('3', 'Shipped'), ('4', 'Delivered'), ('5', 'Canceled')], default=1, max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.CustomerProductCart')),
            ],
        ),
        migrations.RemoveField(
            model_name='customerorders',
            name='order_status',
        ),
        migrations.AddField(
            model_name='orderedproductstatus',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.CustomerOrders'),
        ),
        migrations.AddField(
            model_name='orderedproductstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
