# Generated by Django 2.1.5 on 2019-04-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_customeraddress_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorders',
            name='coupon_id',
        ),
        migrations.AddField(
            model_name='customerorders',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
