# Generated by Django 2.1.5 on 2019-07-22 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0072_productavailablecolourwithsizeqty_is_out_of_stock'),
        ('orders', '0015_auto_20190720_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_reasons', models.CharField(blank=True, max_length=150)),
                ('cancel_description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderedProductStatus')),
            ],
        ),
        migrations.AddField(
            model_name='orderedproductreviews',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
