# Generated by Django 2.1.5 on 2019-07-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20190722_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancelreason',
            old_name='cancel_reasons',
            new_name='cancel_reason',
        ),
    ]
