# Generated by Django 2.1.5 on 2019-07-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20190722_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproductstatus',
            name='order_status',
            field=models.CharField(choices=[('1', 'Ordered'), ('2', 'Packed'), ('3', 'Shipped'), ('4', 'Delivered'), ('5', 'Canceled'), ('6', 'Out for delivery')], default=1, max_length=2),
        ),
    ]
