# Generated by Django 2.1.5 on 2019-07-23 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20190723_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.CharField(blank=True, max_length=150)),
                ('return_description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderedProductStatus')),
            ],
        ),
    ]
