# Generated by Django 2.1.5 on 2019-07-23 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20190723_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundmoneybankdetails',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderedproductstatus',
            name='order_status',
            field=models.CharField(choices=[('1', 'Ordered'), ('2', 'Packed'), ('3', 'Shipped'), ('4', 'Delivered'), ('5', 'Canceled'), ('6', 'Out for delivery'), ('7', 'returned'), ('8', 'return accepted'), ('9', 'return completed and refuned')], default=1, max_length=2),
        ),
    ]
