# Generated by Django 2.1.5 on 2019-07-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20190723_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundmoneybankdetails',
            name='branch_addr',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
