# Generated by Django 2.1.5 on 2019-07-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_refundmoneybankdetails_branch_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='payment',
            field=models.CharField(choices=[('1', 'Card'), ('3', 'Net banking'), ('2', 'Cash on delivery')], max_length=50),
        ),
    ]
