# Generated by Django 2.1.5 on 2019-07-24 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0072_productavailablecolourwithsizeqty_is_out_of_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0026_auto_20190724_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_description', models.TextField(blank=True)),
                ('selected_size', models.CharField(max_length=10)),
                ('selected_quantity', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('previous_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderedProductStatus')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('selected_colour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductAvailableColourWithSizeQty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='exchangereason',
            name='order',
        ),
        migrations.RemoveField(
            model_name='exchangereason',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExchangeReason',
        ),
    ]
