# Generated by Django 2.1.5 on 2019-07-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20190725_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='is_exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerorders',
            name='is_refund_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerorders',
            name='payment',
            field=models.CharField(blank=True, choices=[('1', 'Card'), ('3', 'Net banking'), ('2', 'Cash on delivery')], max_length=50),
        ),
    ]
