# Generated by Django 2.1.5 on 2019-07-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20190725_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundmoneybankdetails',
            name='is_exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refundmoneybankdetails',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
