# Generated by Django 2.1.5 on 2019-07-25 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20190725_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundmoneybankdetails',
            name='exchange_previous_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_previous_order', to='orders.OrderedProductStatus'),
        ),
    ]
