# Generated by Django 2.1.5 on 2019-07-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_refundmoneybankdetails_exchange_previous_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='cart',
            field=models.ManyToManyField(blank=True, to='product.CustomerProductCart'),
        ),
    ]
