# Generated by Django 2.1.5 on 2019-07-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20190725_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproductstatus',
            name='order_status',
            field=models.CharField(choices=[('1', 'Ordered'), ('2', 'Packed'), ('3', 'Shipped'), ('4', 'Delivered'), ('5', 'Canceled'), ('6', 'Out for delivery'), ('7', 'returned'), ('8', 'return accepted'), ('9', 'return completed and refuned'), ('10', 'exchange accepted'), ('11', 'pickup and exchanged')], default=1, max_length=2),
        ),
    ]
