# Generated by Django 2.1.5 on 2019-07-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20190726_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproductstatus',
            name='order_status',
            field=models.CharField(choices=[('1', '0rdered'), ('2', 'Packed'), ('3', 'Shipped'), ('4', 'Delivered'), ('5', 'Cancelled'), ('6', 'Out for delivery'), ('7', 'returned'), ('8', 'return accepted'), ('9', 'return completed and refuned'), ('10', 'exchange'), ('11', 'pickup and exchanged'), ('12', 'delivered and exchanged')], default=1, max_length=2),
        ),
    ]
