# Generated by Django 2.1.5 on 2019-07-30 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_orderstatuschangedate_status_change_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='exchange_previous_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_previous', to='orders.OrderedProductStatus'),
        ),
    ]
