# Generated by Django 2.1.5 on 2019-08-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_auto_20190730_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
