# Generated by Django 2.1.5 on 2019-08-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_auto_20190819_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
