# Generated by Django 2.1.5 on 2020-02-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_auto_20190819_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.TextField(default='')),
                ('file', models.FileField(default='', upload_to='user/profileimg')),
            ],
        ),
    ]
